# The container-based testing process looks nice!
sudo: false
dist: trusty

# Setting the language to C, just because!
language: c

script:
  - bash -x download_terraform_binaries.sh
  - if [ ! -f "$HOME/terraform/linux/terraform" ]; then
      echo -e "Failed! File \"terraform\" not found.";
      exit 1;
    fi
  - $HOME/terraform/linux/terraform -v

