# The container-based testing process looks nice!
sudo: false
dist: trusty

# Setting the language to Go, just because!
language: go
go:
  - 1.8

install:
  - # nothing here!

script:
  - |
    pwd


    # Execute the script with the defaults (which is, download the terraform
    # binary for Linux)
    bash -x download_terraform_binaries.sh

    # Check if there's a file in the expected location, fail otherwise
    if [ ! -f ./bins/linux/terraform ]; then
      echo -e "Failed! File \"terraform\" not found."
      exit 1
    fi

    # As an extra sanity check, check if we can get the terraform version
    ./bins/linux/terraform -v

