# The container-based testing process looks nice!
sudo: false
dist: trusty

# Setting the language to C, just because!
language: c

script:
  - bash download_terraform_binaries.sh
  - if [ ! -f ./bins/linux/terraform ]; then
      echo -e "Failed! File \"terraform\" not found.";
      exit 1;
    fi
  - ./bins/linux/terraform -v
