# The container-based testing process looks nice!
sudo: false
dist: trusty

# Setting the language to C, just because!
language: c

script:
  - bash download_terraform_binaries.sh
  - if [ ! -f "$HOME/terraform/linux/terraform" ]; then
      echo -e "Failed! File \"terraform\" not found.";
      exit 1;
    fi
  - $HOME/terraform/linux/terraform -v
  - rm -rf $HOME/terraform/linux/terraform
  - TF_VERSION=0.9.11 bash download_terraform_binaries
  - if [ ! -f "$HOME/terraform/linux/terraform" ]; then
      echo -e "Failed! File \"terraform\" not found.";
      exit 1;
    fi
  - $HOME/terraform/linux/terraform -v

